import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { courses, branches } from '@/services/mockData';

/**
 * Generate and download PDF for a question paper
 * @param {Object} paper - The paper object containing config and questions
 */
export const downloadQuestionPaperPdf = (paper) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // ... (keep helper functions and previous code) ...

  // To preserve context, I will just provide the full function content if I can't easily jump.
  // Actually, I can just replace the import and the specific call site.
  // But let's rewrite the imports and the specific autoTable call.
  
  const margin = 15;
  let yPos = 20;

  // ... (helpers) ...
  const centerText = (text, y) => {
    const textWidth = doc.getStringUnitWidth(text) * doc.internal.getFontSize() / doc.internal.scaleFactor;
    const x = (pageWidth - textWidth) / 2;
    doc.text(text, x, y);
  };

  const addLine = (y) => {
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    return y + 5;
  };

  // --- Header ---
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  centerText("ACADEMIC ERP INSTITUTE OF TECHNOLOGY", yPos);
  yPos += 8;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  centerText("An Autonomous Institute", yPos);
  yPos += 10;
  
  yPos = addLine(yPos);

  // --- Exam Metadata ---
  const course = courses.find(c => c.id === paper.courseId);
  const branch = branches.find(b => b.id === paper.branchId);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  
  // Left Column
  doc.text(`Course: ${course?.name || paper.config?.courseId || '-' } (${course?.code || '-'})`, margin, yPos);
  yPos += 6;
  doc.text(`Branch: ${branch?.name || paper.config?.branchId || '-'}`, margin, yPos);
  yPos += 6;
  doc.text(`Exam: ${paper.examType === 'end' ? 'End Semester' : 'Mid Semester'}`, margin, yPos);

  // Right Column (same Y as first line)
  const rightX = pageWidth - margin - 60;
  let rightY = yPos - 12;
  
  doc.text(`Date: ${new Date(paper.generatedAt).toLocaleDateString()}`, rightX, rightY);
  rightY += 6;
  doc.text(`Time: 3 Hours`, rightX, rightY); // Default duration or dynamic if available
  rightY += 6;
  doc.text(`Max Marks: ${paper.totalMarks}`, rightX, rightY);

  yPos += 8;
  yPos = addLine(yPos);

  // --- Instructions ---
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text("Instructions:", margin, yPos);
  yPos += 5;
  doc.text("1. Answer all questions.", margin + 5, yPos);
  yPos += 5;
  doc.text("2. Figures to the right indicate full marks.", margin + 5, yPos);
  yPos += 8;
  
  yPos = addLine(yPos);
  yPos += 5;

  // --- Questions Section ---
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  centerText("PART - A (Questions)", yPos);
  yPos += 10;

  // Using autoTable for better layout of questions
  const tableColumn = ["Q.No", "Question", "Unit", "Bloom", "Marks"];
  const tableRows = [];

  paper.questions.forEach((q, index) => {
    tableRows.push([
      index + 1,
      q.questionText,
      `U${q.unitId}`, // Assuming simple unit ID display
      `L${q.bloomLevelId || '-'}`,
      q.marks
    ]);
  });

  autoTable(doc, {
    startY: yPos,
    head: [tableColumn],
    body: tableRows,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 3, overflow: 'linebreak' },
    columnStyles: {
      0: { cellWidth: 15, halign: 'center' },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 15, halign: 'center' },
      3: { cellWidth: 15, halign: 'center' },
      4: { cellWidth: 15, halign: 'right' }
    },
    headStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' }
  });

  // --- Footer ---
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text('Generated by Academic ERP', margin, doc.internal.pageSize.height - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, doc.internal.pageSize.height - 10);
  }

  // --- Save ---
  const filename = `QuestionPaper_${course?.code || 'Exam'}_${Date.now()}.pdf`;
  doc.save(filename);
};
